name: Rust

on:
  push:
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install the toolchain
        run: |
          rustup install nightly-2021-07-06-x86_64-unknown-linux-gnu
          rustup override set nightly-2021-07-06-x86_64-unknown-linux-gnu
      - name: Add rust-src
        run: rustup component add rust-src --toolchain nightly-2021-07-06-x86_64-unknown-linux-gnu
      - name: Build
        run: |
          cargo build --verbose

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        run: bash meta/format-check.sh
